model:
  class_name: model_adaptsplat_infer.HybridDINOMVPModel
  # ConvNeXt configuration
  convnext_type: 'base'  # 'tiny' or 'base'
  dinov3_repo_path: './dinov3/'
  pretrained_path: 'pretrian_weight/dinov3_convnext_base_pretrain_lvd1689m-801f2ba9.pth'
  patch_factor: 2 # half for stage1 training
  mvp_depths: [2, 4, 8]  # Number of transformer blocks in each stage

  num_register_tokens: 4
  head_dim: 64
  inter_multi: 4
  qk_norm: true
  group_size: 4
  patch_size: 8
  in_channels: 12

  gaussians:
    sh_degree: 1
    opacity_degree: 2
    near_plane: 0.01
    far_plane: 1000000.0
    scale_bias: -6.9
    scale_max: -1.2
    opacity_bias: -2.0
    align_to_pixel: true
    max_dist: 500.0

data:
  data_path: "./data_dl3dv/dl3dv_bechmark_140_hf.txt"
  json_path: "data/dl3dv_fold_8_kmeans_input_idx.json"
  resize_h: 544
  square_crop: false

  input_frame_select_type: "kmeans"
  target_frame_select_type: "uniform_every"
  num_input_frames: 32
  num_target_frames: 8
  target_has_input: false
  min_frame_dist: all
  max_frame_dist: all
  shuffle_input_prob: 0.0
  reverse_input_prob: 0.0
  target_uniform_every: 8


training:
  # resume_ckpt: /path/to/cktp
  # reset_training_state: true
  use_amp: true
  use_tf32: true
  amp_dtype: bf16

  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 4
  warmup: 2000
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.95
  lr: 0.0002
  train_steps: 100000
  train_stage: 1

  dataset_name: dataset.Dataset
  checkpoint_dir: './output/'
  checkpoint_every: 1000
  grad_accum_steps: 2
  grad_checkpoint_every: 1 

  l2_loss_weight: 0.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.0

  num_threads: 8
  num_workers: 1
  prefetch_factor: 8
  print_every: 10

  wandb_exp_name: Adaptsplat
  wandb_log_every: 10
  wandb_project: Adaptsplat

  image_height: 544
  image_width: 960
inference:
  dataset_name: dataset.Dataset
  amp_dtype: bf16
  use_amp: true  
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 1
  num_threads: 2
  num_workers: 1
  prefetch_factor: 4  
  use_tf32: true
  target_chunk_size: 8  # 每次处理4个目标帧（平衡配置）
  ckpt_path: checkpoints/ckpt_adaptsplat_dl3dv_960.pt
  out_dir: ./output/dl3dv_960_32view

  compute_metrics: true

